### ISSUE TITLE
DixonColes error message

### ISSUE THREAD

**Issue by R-L-Plates** [Torvaney/regista#30]
Hi,

I've been trying to replicate your "Dixon Coles and xG: together at last" post and keep hitting the error below after trying to run the simulated_games section

Error: Column name `<tibble>` must not be duplicated.
Use .name_repair to specify repair.

Any tips would be greatly appreciated

**Comment by mathlete76** [comment]
Same issue I'm running into.

![image](https://user-images.githubusercontent.com/61978367/77461002-d3727780-6df9-11ea-86fc-12f2b24c3471.png)

**Comment by mathlete76** [comment]
`library(tidyverse)
library(regista)
library(poisbinom)

match.stats <- read.csv('C:\\Users\\David\\Documents\\R\\EPLshotsxG18to20.csv')

match.stats <- select(match.stats, match_id, date, home = h_team, away = a_team, hgoal = h_goals, agoal = a_goals, side = h_a, xg = xG, season)
match.stats <- as_tibble(match.stats)
match.stats$date <- as.Date(match.stats$date)


season1819 <- match.stats %>% filter(season == 2018)
season1819 <- nest(season1819, shots = c(xg, side))
season1819 <- subset(season1819[3:380,])

add_if_missing <- function(data, col, fill = 0.0) {
  # Add column if not found in a dataframe
  # We need this in cases where a team has 0 shots (!)
  if (!(col %in% colnames(data))) {
    data[, col] <- fill
  }
  data
}

team_goal_probs <- function(xgs, side) {
  # Find P(Goals=G) from a set of xGs by the
  # poisson-binomial distribution
  # Use tidyeval to prefix column names with
  # the team's side ("h"ome or "a"way)
  tibble(!!str_c(side, "goals") := 0:length(xgs),
         !!str_c(side, "prob")  := poisbinom::dpoisbinom(0:length(xgs), xgs))
}

simulate_game <- function(shot_xgs) {
  shot_xgs %>%
    split(.$side) %>%
    imap(~ team_goal_probs(.x$xg, .y)) %>%
    reduce(crossing) %>%
    # If there are no shots, give that team a 1.0 chance of scoring 0 goals
    add_if_missing("hgoals", 0) %>%
    add_if_missing("hprob", 1) %>%
    add_if_missing("agoals", 0) %>%
    add_if_missing("aprob", 1) %>%
    mutate(prob = hprob * aprob) %>%
    select(hgoals, agoals, prob)
}

simulated_games <-
  season1819 %>%
  mutate(simulated_probabilities = map(shots, simulate_game)) %>%
  select(match_id, home, away, simulated_probabilities) %>%
  unnest() %>%
  filter(prob > 0.001)  # Keep the number of rows vaguely reasonable
#> Error: Column name `<tibble>` must not be duplicated.
#> Use .name_repair to specify repair.

print(simulated_games)
#> Error in print(simulated_games): object 'simulated_games' not found`

**Comment by mathlete76** [comment]
I'm getting the same issue. Created a dataframe called season1819 with the same structure as the one in the blog.


> simulated_games <-
>   season1819 %>%
>   mutate(simulated_probabilities = map(shots, simulate_game)) %>%
>   select(match_id, home, away, simulated_probabilities) %>%
>   unnest() %>%
>   filter(prob > 0.001)  # Keep the number of rows vaguely reasonable
> #> Error: Column name `<tibble>` must not be duplicated.
> #> Use .name_repair to specify repair.

**Comment by Torvaney** [comment]
Hi folks - this issue is because the notebook was written with an older version of tidyr. The latest version introduced some changes around column naming which breaks the code as-is. A few people have mentioned this to me, but I haven't (yet) gotten around to updating the blog.

If I remember correctly, the issue is in how `reduce(crossing)` works (in `simulate_game`) with column names.

One fix I can suggest is to refactor the `simulate_game` function to something like

```r
simulate_shots <- function(xgs) {
  tibble::tibble(goal = 0:length(xgs),
                 prob = poisbinom::dpoisbinom(0:length(xgs), xgs))
}

simulate_game <- function(shot_xgs) {
  home_xgs <- shot_xgs %>% dplyr::filter(side == "h")
  away_xgs <- shot_xgs %>% dplyr::filter(side == "a")

  home_probs <- simulate_shots(home_xgs) %>% dplyr::rename_all(function(x) paste0("h", x))
  away_probs <- simulate_shots(away_xgs) %>% dplyr::rename_all(function(x) paste0("a", x))

  tidyr::crossing(home_probs, away_probs) %>%
    dplyr::mutate(prob = .data$hprob * .data$aprob)
}
```

(this also means you can get rid of the `add_if_missing` and `team_goal_probs` functions).

Hope that helps! Let me know if not :)

**Comment by mathlete76** [comment]
Hi, thanks for quick reply!

The replacement code errors as it tries to pass a list to dpoisbinom, so I adjusted it as follows:

`home_probs <- simulate_shots(home_xgs$xg) %>% dplyr::rename_all(function(x) paste0("h", x))
away_probs <- simulate_shots(away_xgs$xg) %>% dplyr::rename_all(function(x) paste0("a", x))
`
so that it gets the numeric values from the xg column. It crashed a few times on first attempts to run,, but runs fine now. It does end with a warning message, but the simulated_games tibble exists regardless.

> Warning message:
`cols` is now required.
Please use `cols = c(simulated_probabilities)`

**Comment by Torvaney** [comment]
Ah perfect, thanks!

**Comment by Torvaney** [comment]
I've updated the blog post to reflect this (http://www.statsandsnakeoil.com/2018/06/22/dixon-coles-and-xg-together-at-last/)

Let me know if you'd like a name/link dropped in the post (currently I'm just linking back to this issue).

Thanks again!
